function auth(r){return Boolean(process.env.ADMIN_PASSWORD)&&String(r.headers['x-admin-password']||'')===process.env.ADMIN_PASSWORD;}
function config(){return {url:String(process.env.SUPABASE_URL||'').trim().replace(/^['"]|['"]$/g,'').replace(/\/rest\/v1\/?$/i,'').replace(/\/+$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY};}
async function sb(path,options={}){const {url,key}=config();if(!url||!key)throw new Error('Faltan variables de conexión con Supabase.');const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json',...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||d?.details||'Supabase no pudo completar la operación.');return d;}
const clean=v=>String(v||'').trim();
function payload(b){return {nombre:clean(b.nombre),tipo:clean(b.tipo)||'rifa',producto_nombre:clean(b.producto_nombre),imagen_url:clean(b.imagen_url),descripcion:clean(b.descripcion),fecha_sorteo:b.fecha_sorteo||null,limite_boletos:Number(b.limite_boletos),cantidad_ganadores:Number(b.cantidad_ganadores||1),estado:['borrador','abierta','cerrada','finalizada'].includes(b.estado)?b.estado:'borrador',mostrar_contador:b.mostrar_contador!==false,mostrar_participantes:b.mostrar_participantes===true,publicar_ganador:b.publicar_ganador!==false,prefijo:(clean(b.prefijo)||'ANI').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8),actualizado_en:new Date().toISOString()};}
export default async function handler(req,res){if(!auth(req))return res.status(401).json({error:'Contraseña de administrador incorrecta.'});res.setHeader('Cache-Control','no-store');try{const action=clean(req.query?.action);
 if(req.method==='GET'&&action==='participantes'){const id=Number(req.query?.evento_id);const data=await sb(`participantes_evento?select=id,numero,codigo,nombre,telefono,ciudad,activo,fecha_registro&evento_id=eq.${id}&order=numero.asc`);return res.status(200).json(data);}
 if(req.method==='GET'&&action==='ganadores'){const id=Number(req.query?.evento_id);const data=await sb(`ganadores_evento?select=id,posicion,publicado,premio_entregado,fecha_sorteo,participantes_evento(id,numero,codigo,nombre,telefono,ciudad)&evento_id=eq.${id}&order=posicion.asc`);return res.status(200).json(data);}
 if(req.method==='POST'&&action==='sortear'){const id=Number(req.body?.evento_id);const ev=(await sb(`eventos_comunidad?select=id,cantidad_ganadores,estado&izar=id&id=eq.${id}&limit=1`.replace('&izar=id','')))?.[0];if(!ev) return res.status(404).json({error:'Evento no encontrado.'});const existing=await sb(`ganadores_evento?select=participante_id&evento_id=eq.${id}`);const excluded=new Set((existing||[]).map(x=>x.participante_id));const participants=await sb(`participantes_evento?select=id,numero,codigo,nombre,telefono,ciudad&evento_id=eq.${id}&activo=eq.true`);const pool=(participants||[]).filter(x=>!excluded.has(x.id));const needed=Math.max(0,Number(ev.cantidad_ganadores)-excluded.size);if(pool.length<needed||needed===0){if(needed===0)return res.status(409).json({error:'Este evento ya tiene todos sus ganadores.'});return res.status(409).json({error:'No hay suficientes participantes disponibles.'});}for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}const chosen=pool.slice(0,needed);const rows=chosen.map((p,i)=>({evento_id:id,participante_id:p.id,posicion:excluded.size+i+1,publicado:true}));await sb('ganadores_evento',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(rows)});await sb(`eventos_comunidad?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({estado:'finalizada',actualizado_en:new Date().toISOString()})});return res.status(200).json(chosen);}
 if(req.method==='PATCH'&&action==='ganador'){const id=Number(req.body?.id);const body={};if(typeof req.body?.publicado==='boolean')body.publicado=req.body.publicado;if(typeof req.body?.premio_entregado==='boolean')body.premio_entregado=req.body.premio_entregado;await sb(`ganadores_evento?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});return res.status(200).json({ok:true});}
 if(req.method==='GET'){const data=await sb('eventos_comunidad?select=*&order=creado_en.desc');for(const e of data||[]){const p=await sb(`participantes_evento?select=id&evento_id=eq.${e.id}`);e.participantes_count=p?.length||0;}return res.status(200).json(data);}
 if(req.method==='POST'){const p=payload(req.body||{});if(!p.nombre||!p.producto_nombre||!Number.isInteger(p.limite_boletos)||p.limite_boletos<1)return res.status(400).json({error:'Nombre, producto y límite de boletos son obligatorios.'});const d=await sb('eventos_comunidad',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(p)});return res.status(201).json(d?.[0]||d);}
 if(req.method==='PUT'){const id=Number(req.body?.id),p=payload(req.body||{});if(!id)return res.status(400).json({error:'Evento no válido.'});const d=await sb(`eventos_comunidad?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(p)});return res.status(200).json(d?.[0]||d);}
 if(req.method==='DELETE'){const id=Number(req.query?.id);await sb(`eventos_comunidad?id=eq.${id}`,{method:'DELETE'});return res.status(204).end();}
 res.setHeader('Allow','GET, POST, PUT, PATCH, DELETE');return res.status(405).json({error:'Método no permitido.'});
 }catch(e){return res.status(500).json({error:e.message||'Error interno.'});}}
