function config(){return {url:String(process.env.SUPABASE_URL||'').trim().replace(/^['"]|['"]$/g,'').replace(/\/rest\/v1\/?$/i,'').replace(/\/+$/,''),key:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY};}
async function sb(path,options={}){const {url,key}=config();if(!url||!key)throw new Error('Faltan variables de conexión con Supabase.');const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json',...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||d?.details||'No fue posible completar la operación.');return d;}
const clean=v=>String(v||'').trim();
const phone=v=>clean(v).replace(/\D/g,'');
function publicEvent(e,count,winners){return {...e,participantes_count:count,disponibles:Math.max(0,Number(e.limite_boletos)-count),ganadores:winners.map(w=>({posicion:w.posicion,numero:w.participantes_evento?.numero,codigo:w.participantes_evento?.codigo,nombre_parcial:(clean(w.participantes_evento?.nombre).split(/\s+/)[0]||'Participante')+' '+((clean(w.participantes_evento?.nombre).split(/\s+/)[1]||'').slice(0,1)+(clean(w.participantes_evento?.nombre).split(/\s+/)[1]?'．':''))}))};}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{
 if(req.method==='GET'&&req.query?.action==='consulta'){const eventoId=Number(req.query?.evento_id);const tel=phone(req.query?.telefono);if(!eventoId||tel.length!==10)return res.status(400).json({error:'Ingresa un teléfono válido de 10 dígitos.'});const rows=await sb(`participantes_evento?select=numero,codigo,nombre,ciudad,fecha_registro&evento_id=eq.${eventoId}&telefono=eq.${tel}&limit=1`);if(!rows?.length)return res.status(404).json({error:'No encontramos un registro con ese teléfono.'});return res.status(200).json(rows[0]);}
 if(req.method==='GET'){const events=await sb('eventos_comunidad?select=id,nombre,tipo,producto_nombre,imagen_url,descripcion,fecha_sorteo,limite_boletos,cantidad_ganadores,estado,mostrar_contador,mostrar_participantes,publicar_ganador,prefijo&estado=in.(abierta,cerrada,finalizada)&order=creado_en.desc&limit=1');if(!events?.length)return res.status(200).json({evento:null});const e=events[0];const countRows=await sb(`participantes_evento?select=id&evento_id=eq.${e.id}&activo=eq.true`);let winners=[];if(e.publicar_ganador){winners=await sb(`ganadores_evento?select=posicion,participantes_evento(numero,codigo,nombre)&evento_id=eq.${e.id}&publicado=eq.true&order=posicion.asc`);}return res.status(200).json({evento:publicEvent(e,countRows?.length||0,winners||[])});}
 if(req.method==='POST'){const eventoId=Number(req.body?.evento_id),nombre=clean(req.body?.nombre),tel=phone(req.body?.telefono),ciudad=clean(req.body?.ciudad);if(!eventoId||nombre.length<3)return res.status(400).json({error:'Escribe tu nombre completo.'});if(tel.length!==10)return res.status(400).json({error:'Ingresa un teléfono válido de 10 dígitos.'});if(req.body?.acepta_privacidad!==true)return res.status(400).json({error:'Debes aceptar el aviso de privacidad.'});const data=await sb('rpc/registrar_participante_evento',{method:'POST',body:JSON.stringify({p_evento_id:eventoId,p_nombre:nombre,p_telefono:tel,p_ciudad:ciudad})});return res.status(201).json(data?.[0]||data);}
 res.setHeader('Allow','GET, POST');return res.status(405).json({error:'Método no permitido.'});
 }catch(e){const msg=e.message||'Error interno.';const status=/cerrados|agotado|existe/i.test(msg)?409:500;return res.status(status).json({error:msg});}}
